agent_type: smol
max_num_steps: 100
tools: [list_dir, maven_install, duckduckgo, stateful_file_tool]
model_name: gemini/gemini-2.0-flash
prompt: Upgrade the Maven project rooted at the current working dir to use JDK 17. Ensure that the build and the tests pass. You can make source code and dependnecy changes. You cannot delete or comment-out tests.