max_num_steps: 50
tools: [read_file, write_file, list_dir, maven_install, duckduckgo]
model_name: gemini/gemini-1.5-pro
prompt: Upgrade the project to use JDK 17. Ensure that the build and the tests pass.